# Dependencies
# markdown:         redcarpet
highlighter:      pygments

gems:             [jekyll-paginate]

# Setup
title:            Project Model S
tagline:          'Parallel Variational Shape Approximation for simplifying 3D scanned dense meshes'
description:      'Parallel Variational Shape Approximation for simplifying 3D scanned dense meshes'
url:              https://zwmj9304.github.io/ModelS
baseurl:          https://zwmj9304.github.io/ModelS/

author:
  name:           'George Zhu and Min Park'
  url:            https://zwmj9304.github.io/resume/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/zwmj9304/ModelS
